[package]
name = "noise-textures"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
palette = "0.6.0"
sdl2 = { version = "0.34.5", features = ["bundled"] }
itertools = "0.10.1"
